### PR TITLE
Added bcrypt jwt and formated code

### PR DESCRIPTION
**Pull request by Naresh-chandanbatve**

### CODE REVIEW

**Comment by Naresh-chandanbatve** [comment]
@Siddhant-Patil0203

**Review by Siddhant-Patil0203 — COMMENTED** [review]
Chagne the token validity for atleast 1d to test the routes properly and later do it to 7d in production, also add a constraint, that if token is invalid then it gets logged out automatically, if it is in logged in session

**Review by Siddhant-Patil0203 — APPROVED** [review]
This are good to go 👍

**Comment by Siddhant-Patil0203** [comment]
@Naresh-chandanbatve 

Also, make the issues for the things you are working on to make proper project management and tracking.

**Pull request merged**
