### PR TITLE
Added a Folder for Logo in the assets folder, updated readme (figma link)

### PR DESCRIPTION
**Pull request by LadeHarshal**
Added Figma Link and Logo Folder in assets as was told to do so.

### CODE REVIEW

**Comment by LadeHarshal** [comment]
@Siddhant-Patil0203

**Review by Siddhant-Patil0203 — APPROVED** [review]
Seems good 👍

**Comment by Siddhant-Patil0203** [comment]
Please ensure that the Figma link you have provided is set to view-only access.
@LadeHarshal

**Comment by LadeHarshal** [comment]
> Please ensure that the Figma link you have provided is set to view-only access. @LadeHarshal

Thanks for the heads up @Siddhant-Patil0203 
Have changed the access settings , It should be fine now

**Review by Siddhant-Patil0203 — CHANGES_REQUESTED** [review]
Please pull the previous changes before proceeding.You haven't pulled the previous changes pls. do it first

**Comment by LadeHarshal** [comment]
> Please pull the previous changes before proceeding. @LadeHarshal

Did that👍🏼

**Comment by Siddhant-Patil0203** [comment]
The pop-up requesting access to the link should not appear, as the content is intended to be viewable by anyone. 


@LadeHarshal

**Comment by LadeHarshal** [comment]
> The pop-up requesting access to the link should not appear, as the content is intended to be viewable by anyone. 
> 
> @LadeHarshal

image

**Review by Siddhant-Patil0203 — APPROVED** [review]
Looks Good

**Pull request merged**
