### PR TITLE
added profile edit section for all users

### PR DESCRIPTION
**Pull request by Naresh-chandanbatve**
- [x]  profile edit routes
- [x]  password change route

### CODE REVIEW

**Comment by Naresh-chandanbatve** [comment]
done 
can be merged
codeql succeeded


precaution to take 
it will require all the fields to be non empty to make any request for now.

**Comment by Naresh-chandanbatve** [comment]
Need to find a way to pass codeql scanning even without the need to fill all the fields.

**Comment by Naresh-chandanbatve** [comment]
@Siddhant-Patil0203 
review this first this is big pr and merging this will automatically reduce file changed in other prs

**Comment by Siddhant-Patil0203** [comment]
Sure @Naresh-chandanbatve 
Will be done by tomorrow

**Review by Siddhant-Patil0203 — APPROVED** [review]
Good to go 👍

**Comment by Siddhant-Patil0203** [comment]
Deployment Working Properly 👍

**Pull request merged**
